# Generated by Django 4.2.1 on 2023-05-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='cantidad',
        ),
    ]
